export const siteConfig = {
  language: "en",
  brandName: "SLIIT Library",
  copyright: "(c) 2026 SLIIT Library",
};

export const navigationConfig = {
  infoLinkLabel: "About",
};

export const infoPageConfig = {
  backLinkLabel: "Back",
  eyebrow: "Sri Lanka Institute of Information Technology",
  title: "Discover Knowledge. Empower Your Future.",
  paragraphs: [
    "The SLIIT Library stands as the intellectual heart of the Sri Lanka Institute of Information Technology, serving over 15,000 students, faculty, and researchers. Our collection spans more than 50,000 physical volumes and 100,000+ digital resources, covering computing, engineering, business, humanities, and sciences.",
    "Founded alongside the university in 1999, the library has evolved from a modest reading room to a state-of-the-art learning commons. Our Online Library Management System represents the next chapter in this evolution, providing seamless digital access to our entire collection.",
    "We believe that knowledge should be accessible, inclusive, and empowering. Whether you are an undergraduate seeking course materials, a postgraduate researcher exploring cutting-edge publications, or a faculty member developing new curricula, the SLIIT Library is your partner in academic excellence.",
  ],
  contactLabel: "Contact",
  contactEntries: [
    { label: "Email", value: "library@sliit.lk", href: "mailto:library@sliit.lk" },
    { label: "Phone", value: "+94 11 754 4801", href: "tel:+94117544801" },
    { label: "Location", value: "SLIIT Main Campus, Malabe\nNew Kandy Road, Colombo" },
    { label: "Hours", value: "Mon-Fri: 08:00-20:00\nSat: 09:00-17:00\nSun: Closed" },
    { label: "Portal", value: "sliit.lk/library", href: "https://www.sliit.lk" },
  ],
};

export const overlayConfig = {
  frameDetailLabel: "Book Detail",
  fileLabel: "ISBN",
  seriesLabel: "Category",
  closeLabel: "Close",
};

export const galleryConfig = {
  images: [
    {
      src: "/images/book_01.jpg",
      category: "Fiction",
      title: "The Great Gatsby",
      description:
        "F. Scott Fitzgerald's masterpiece of the Jazz Age. A story of decadence, idealism, and the American Dream set in the Roaring Twenties. Explore themes of wealth, society, and the corrupting influence of money through the eyes of narrator Nick Carraway.",
    },
    {
      src: "/images/book_02.jpg",
      category: "Technology",
      title: "Introduction to Algorithms",
      description:
        "The definitive guide to algorithms by Cormen, Leiserson, Rivest, and Stein. Covers a broad range of algorithms in depth, making their design and analysis accessible to all levels of readers. Essential for every computer science student.",
    },
    {
      src: "/images/book_03.jpg",
      category: "Science",
      title: "A Brief History of Time",
      description:
        "Stephen Hawking's landmark volume in science writing. Explores the nature of time, black holes, the Big Bang, and the quest for a unified theory of everything. A mind-expanding journey through cosmology that makes complex concepts accessible.",
    },
    {
      src: "/images/book_04.jpg",
      category: "Technology",
      title: "Clean Code",
      description:
        "Robert C. Martin's essential handbook of agile software craftsmanship. Learn to write code that is clean, maintainable, and professional. A must-read for any developer who wants to elevate their craft and produce better software.",
    },
    {
      src: "/images/book_05.jpg",
      category: "Fiction",
      title: "Pride and Prejudice",
      description:
        "Jane Austen's beloved comedy of manners that brilliantly lampoons the societal norms of Regency-era England. The story follows Elizabeth Bennet as she navigates issues of love, reputation, and class with wit and independence.",
    },
    {
      src: "/images/book_06.jpg",
      category: "Technology",
      title: "Design Patterns",
      description:
        "The seminal Gang of Four book on software design patterns. Learn the fundamental patterns that every object-oriented developer should know: Singleton, Observer, Factory, Strategy, and more. The foundation of reusable software architecture.",
    },
    {
      src: "/images/book_07.jpg",
      category: "History",
      title: "The Art of War",
      description:
        "Sun Tzu's ancient Chinese treatise on military strategy remains one of the most influential works on strategy and tactics ever written. Its principles extend far beyond warfare into business, politics, and everyday decision-making.",
    },
    {
      src: "/images/book_08.jpg",
      category: "Fiction",
      title: "To Kill a Mockingbird",
      description:
        "Harper Lee's Pulitzer Prize-winning novel exploring racial injustice in the American South through the innocent eyes of Scout Finch. A profound examination of moral growth, compassion, and the deep-seated prejudices that shape society.",
    },
    {
      src: "/images/book_09.jpg",
      category: "Technology",
      title: "Database Systems",
      description:
        "A comprehensive guide to the principles of data storage and retrieval. Covers relational database design, SQL, normalization, transaction management, and modern NoSQL systems. Essential for understanding how data powers the modern world.",
    },
    {
      src: "/images/book_10.jpg",
      category: "Science",
      title: "Sapiens",
      description:
        "Yuval Noah Harari's sweeping narrative of human history. From the emergence of Homo sapiens in Africa to the present day, Harari explores how biology and history have defined us and enhanced our understanding of what it means to be human.",
    },
    {
      src: "/images/book_11.jpg",
      category: "Fiction",
      title: "1984",
      description:
        "George Orwell's dystopian masterpiece depicts a totalitarian society under the watchful eye of Big Brother. A chilling prophecy about surveillance, propaganda, and the destruction of truth that remains profoundly relevant in the digital age.",
    },
    {
      src: "/images/book_12.jpg",
      category: "Technology",
      title: "Operating System Concepts",
      description:
        "Silberschatz, Galvin, and Gagne's comprehensive guide to operating systems. Covers process management, memory management, file systems, and distributed systems. The standard textbook for understanding how computers work at the system level.",
    },
    {
      src: "/images/book_13.jpg",
      category: "Literature",
      title: "The Elements of Style",
      description:
        "Strunk and White's timeless guide to writing well. This concise manual offers fundamental advice on grammar, composition, and style that has guided generations of writers. The essential reference for anyone who wants to communicate clearly.",
    },
    {
      src: "/images/book_14.jpg",
      category: "Technology",
      title: "Machine Learning",
      description:
        "A comprehensive guide to artificial intelligence and machine learning. Covers supervised and unsupervised learning, neural networks, deep learning, reinforcement learning, and the mathematical foundations that power modern AI systems.",
    },
    {
      src: "/images/book_15.jpg",
      category: "Fiction",
      title: "Moby Dick",
      description:
        "Herman Melville's epic tale of Captain Ahab's obsessive quest for the white whale. A profound meditation on fate, free will, and the human condition that stands as one of the greatest American novels ever written.",
    },
    {
      src: "/images/book_16.jpg",
      category: "Technology",
      title: "Computer Networks",
      description:
        "Explore the architecture and protocols that power the Internet. From TCP/IP to HTTP, from Ethernet to wireless networks, this comprehensive guide covers every layer of the network stack and prepares you for the connected world.",
    },
    {
      src: "/images/book_17.jpg",
      category: "Fiction",
      title: "Frankenstein",
      description:
        "Mary Shelley's groundbreaking novel about a scientist who creates a sentient creature. The original science fiction story explores themes of ambition, responsibility, and what it means to be human. As relevant today as it was in 1818.",
    },
    {
      src: "/images/book_18.jpg",
      category: "Technology",
      title: "Data Structures in Java",
      description:
        "Master the fundamental data structures and algorithms using Java. From arrays and linked lists to trees, graphs, and hash tables, this practical guide provides implementations, complexity analysis, and real-world applications.",
    },
    {
      src: "/images/book_19.jpg",
      category: "Fiction",
      title: "The Catcher in the Rye",
      description:
        "J.D. Salinger's iconic novel follows Holden Caulfield's journey through post-war New York City. A raw and honest exploration of teenage alienation, identity, and the painful transition from adolescence to adulthood.",
    },
    {
      src: "/images/book_20.jpg",
      category: "Technology",
      title: "Artificial Intelligence",
      description:
        "Russell and Norvig's definitive textbook on AI. Covers intelligent agents, search algorithms, knowledge representation, machine learning, natural language processing, and robotics. The gold standard reference for AI education worldwide.",
    },
  ],
};

export const booksData = [
  {
    id: "BK-001",
    src: "/images/book_01.jpg",
    category: "Fiction",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "F. Scott Fitzgerald's masterpiece of the Jazz Age exploring the American Dream.",
    isbn: "978-0743273565",
    publisher: "Scribner",
    year: 1925,
    format: "Physical",
    copies: 5,
    available: 2,
    ddc: "813.52",
  },
  {
    id: "BK-002",
    src: "/images/book_02.jpg",
    category: "Technology",
    title: "Introduction to Algorithms",
    author: "Cormen, Leiserson, Rivest, Stein",
    description: "The definitive guide to algorithms covering design and analysis.",
    isbn: "978-0262033848",
    publisher: "MIT Press",
    year: 2009,
    format: "Physical",
    copies: 8,
    available: 4,
    ddc: "005.1",
  },
  {
    id: "BK-003",
    src: "/images/book_03.jpg",
    category: "Science",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    description: "A landmark volume exploring cosmology, black holes, and the nature of time.",
    isbn: "978-0553380163",
    publisher: "Bantam",
    year: 1988,
    format: "Physical",
    copies: 6,
    available: 1,
    ddc: "523.1",
  },
  {
    id: "BK-004",
    src: "/images/book_04.jpg",
    category: "Technology",
    title: "Clean Code",
    author: "Robert C. Martin",
    description: "A handbook of agile software craftsmanship for writing maintainable code.",
    isbn: "978-0132350884",
    publisher: "Prentice Hall",
    year: 2008,
    format: "Physical",
    copies: 10,
    available: 7,
    ddc: "005.12",
  },
  {
    id: "BK-005",
    src: "/images/book_05.jpg",
    category: "Fiction",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A beloved comedy of manners lampooning Regency-era societal norms.",
    isbn: "978-0141439518",
    publisher: "Penguin Classics",
    year: 1813,
    format: "Physical",
    copies: 4,
    available: 0,
    ddc: "823.7",
  },
  {
    id: "BK-006",
    src: "/images/book_06.jpg",
    category: "Technology",
    title: "Design Patterns",
    author: "Gamma, Helm, Johnson, Vlissides",
    description: "The seminal Gang of Four book on reusable software design patterns.",
    isbn: "978-0201633610",
    publisher: "Addison-Wesley",
    year: 1994,
    format: "Physical",
    copies: 6,
    available: 3,
    ddc: "005.12",
  },
  {
    id: "BK-007",
    src: "/images/book_07.jpg",
    category: "History",
    title: "The Art of War",
    author: "Sun Tzu",
    description: "Ancient Chinese treatise on military strategy and tactics.",
    isbn: "978-0140439199",
    publisher: "Penguin Classics",
    year: -500,
    format: "Physical",
    copies: 7,
    available: 5,
    ddc: "355.02",
  },
  {
    id: "BK-008",
    src: "/images/book_08.jpg",
    category: "Fiction",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A Pulitzer Prize-winning novel exploring racial injustice in the American South.",
    isbn: "978-0061120084",
    publisher: "Harper Perennial",
    year: 1960,
    format: "Physical",
    copies: 5,
    available: 2,
    ddc: "813.54",
  },
  {
    id: "BK-009",
    src: "/images/book_09.jpg",
    category: "Technology",
    title: "Database Systems",
    author: "J. Chen & R. Sharma",
    description: "Comprehensive guide to data storage, retrieval, and database design.",
    isbn: "978-0133970777",
    publisher: "TechPress",
    year: 2021,
    format: "Physical",
    copies: 8,
    available: 6,
    ddc: "005.74",
  },
  {
    id: "BK-010",
    src: "/images/book_10.jpg",
    category: "Science",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    description: "A sweeping narrative of human history from the Stone Age to the present.",
    isbn: "978-0062316097",
    publisher: "Harper",
    year: 2015,
    format: "Physical",
    copies: 9,
    available: 4,
    ddc: "909",
  },
  {
    id: "BK-011",
    src: "/images/book_11.jpg",
    category: "Fiction",
    title: "1984",
    author: "George Orwell",
    description: "A dystopian masterpiece about totalitarianism, surveillance, and truth.",
    isbn: "978-0451524935",
    publisher: "Signet Classic",
    year: 1949,
    format: "Physical",
    copies: 7,
    available: 3,
    ddc: "823.912",
  },
  {
    id: "BK-012",
    src: "/images/book_12.jpg",
    category: "Technology",
    title: "Operating System Concepts",
    author: "Silberschatz, Galvin, Gagne",
    description: "Comprehensive guide to OS fundamentals: processes, memory, files, and more.",
    isbn: "978-1118063330",
    publisher: "Wiley",
    year: 2012,
    format: "Physical",
    copies: 6,
    available: 2,
    ddc: "005.43",
  },
  {
    id: "BK-013",
    src: "/images/book_13.jpg",
    category: "Literature",
    title: "The Elements of Style",
    author: "Strunk & White",
    description: "The timeless guide to writing well with clear, concise advice.",
    isbn: "978-0205309023",
    publisher: "Pearson",
    year: 1999,
    format: "Physical",
    copies: 12,
    available: 9,
    ddc: "808.042",
  },
  {
    id: "BK-014",
    src: "/images/book_14.jpg",
    category: "Technology",
    title: "Machine Learning: A Comprehensive Guide",
    author: "John Doe",
    description: "Covers supervised, unsupervised, and reinforcement learning paradigms.",
    isbn: "978-0262048446",
    publisher: "AI Press",
    year: 2023,
    format: "eBook",
    copies: 999,
    available: 999,
    ddc: "006.31",
  },
  {
    id: "BK-015",
    src: "/images/book_15.jpg",
    category: "Fiction",
    title: "Moby Dick",
    author: "Herman Melville",
    description: "An epic tale of obsession and the sea, one of the greatest American novels.",
    isbn: "978-0142437247",
    publisher: "Penguin Classics",
    year: 1851,
    format: "Physical",
    copies: 4,
    available: 1,
    ddc: "813.3",
  },
  {
    id: "BK-016",
    src: "/images/book_16.jpg",
    category: "Technology",
    title: "Computer Networks",
    author: "Dr. Anya Sharma",
    description: "Explore network architecture, protocols, and the layers of the Internet.",
    isbn: "978-0133594141",
    publisher: "TechPress",
    year: 2020,
    format: "Physical",
    copies: 7,
    available: 4,
    ddc: "004.6",
  },
  {
    id: "BK-017",
    src: "/images/book_17.jpg",
    category: "Fiction",
    title: "Frankenstein",
    author: "Mary Shelley",
    description: "The original science fiction novel about creation, ambition, and responsibility.",
    isbn: "978-0141439471",
    publisher: "Penguin Classics",
    year: 1818,
    format: "Physical",
    copies: 5,
    available: 2,
    ddc: "823.7",
  },
  {
    id: "BK-018",
    src: "/images/book_18.jpg",
    category: "Technology",
    title: "Data Structures and Algorithms in Java",
    author: "Anna Lee",
    description: "Master fundamental data structures with practical Java implementations.",
    isbn: "978-0132576278",
    publisher: "CodePress",
    year: 2019,
    format: "Physical",
    copies: 8,
    available: 5,
    ddc: "005.13",
  },
  {
    id: "BK-019",
    src: "/images/book_19.jpg",
    category: "Fiction",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    description: "A raw exploration of teenage alienation and the loss of innocence.",
    isbn: "978-0316769488",
    publisher: "Little, Brown",
    year: 1951,
    format: "Physical",
    copies: 6,
    available: 0,
    ddc: "813.54",
  },
  {
    id: "BK-020",
    src: "/images/book_20.jpg",
    category: "Technology",
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell & Peter Norvig",
    description: "The gold standard AI textbook covering agents, search, NLP, and robotics.",
    isbn: "978-0134610993",
    publisher: "Pearson",
    year: 2020,
    format: "Physical",
    copies: 10,
    available: 6,
    ddc: "006.3",
  },
];
